import { NextRequest, NextResponse } from "next/server";
import { answer } from "@/lib/assistant";

export const dynamic = "force-dynamic";

/**
 * WhatsApp Business (Cloud API) webhook.
 *
 * GET  — Meta's verification handshake (hub.challenge echo).
 * POST — inbound messages; replies are generated by the shared Lumi engine and
 *        sent via the Graph API when WHATSAPP_ACCESS_TOKEN is configured.
 *
 * Setup guide: docs/BOTS.md
 */

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const mode = searchParams.get("hub.mode");
  const token = searchParams.get("hub.verify_token");
  const challenge = searchParams.get("hub.challenge");

  if (mode === "subscribe" && token === process.env.WHATSAPP_VERIFY_TOKEN && challenge) {
    return new NextResponse(challenge, { status: 200 });
  }
  return NextResponse.json({ error: "Verification failed." }, { status: 403 });
}

type WhatsAppWebhookPayload = {
  entry?: Array<{
    changes?: Array<{
      value?: {
        messages?: Array<{
          from: string;
          type: string;
          text?: { body: string };
        }>;
      };
    }>;
  }>;
};

export async function POST(req: NextRequest) {
  let payload: WhatsAppWebhookPayload;
  try {
    payload = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid payload." }, { status: 400 });
  }

  const message = payload.entry?.[0]?.changes?.[0]?.value?.messages?.[0];

  if (message?.type === "text" && message.text?.body) {
    const reply = answer(message.text.body);

    const token = process.env.WHATSAPP_ACCESS_TOKEN;
    const phoneNumberId = process.env.WHATSAPP_PHONE_NUMBER_ID;

    if (token && phoneNumberId) {
      await fetch(`https://graph.facebook.com/v19.0/${phoneNumberId}/messages`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          messaging_product: "whatsapp",
          to: message.from,
          type: "text",
          text: { body: reply },
        }),
      }).catch(() => {
        /* Delivery failures are retried by Meta's webhook redelivery. */
      });
    }
  }

  // Always 200 so Meta doesn't disable the webhook.
  return NextResponse.json({ received: true });
}
