import Link from "next/link";
import { demoOrders } from "@/lib/demo-account";
import { formatCurrency, cn } from "@/lib/utils";

const statusStyles: Record<string, string> = {
  delivered: "!border-emerald-500/30 !bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
  out_for_delivery: "!border-aqua-500/30 !bg-aqua-500/10 text-aqua-600 dark:text-aqua-400",
  processing: "!border-violet-500/30 !bg-violet-500/10 text-violet-600 dark:text-violet-400",
  scheduled: "!border-amber-500/30 !bg-amber-500/10 text-amber-600 dark:text-amber-400",
};

const statusLabels: Record<string, string> = {
  delivered: "Delivered",
  out_for_delivery: "Out for delivery",
  processing: "Cleaning",
  scheduled: "Scheduled",
};

export default function OrdersPage() {
  return (
    <div className="card overflow-x-auto p-6 sm:p-8">
      <h2 className="h-display mb-6 text-xl">Order history</h2>
      <table className="w-full min-w-[640px] text-sm">
        <thead>
          <tr className="border-b border-[rgb(var(--border))] text-left text-xs uppercase tracking-wider text-muted">
            <th className="pb-3 pr-4 font-semibold">Order</th>
            <th className="pb-3 pr-4 font-semibold">Service</th>
            <th className="pb-3 pr-4 font-semibold">Date</th>
            <th className="pb-3 pr-4 font-semibold">Status</th>
            <th className="pb-3 pr-4 text-right font-semibold">Total</th>
            <th className="pb-3 text-right font-semibold">Points</th>
            <th className="pb-3" />
          </tr>
        </thead>
        <tbody>
          {demoOrders.map((o) => (
            <tr key={o.id} className="border-b border-[rgb(var(--border))]/60 last:border-0">
              <td className="py-4 pr-4 font-mono text-xs font-semibold">{o.id}</td>
              <td className="py-4 pr-4 font-medium">
                {o.service}
                {o.weightLbs ? <span className="text-muted"> · {o.weightLbs} lbs</span> : null}
              </td>
              <td className="py-4 pr-4 text-muted">
                {new Date(o.date).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
              </td>
              <td className="py-4 pr-4">
                <span className={cn("chip", statusStyles[o.status])}>{statusLabels[o.status]}</span>
              </td>
              <td className="py-4 pr-4 text-right font-display font-bold">{formatCurrency(o.total)}</td>
              <td className="py-4 text-right font-semibold text-emerald-500">+{o.points}</td>
              <td className="py-4 pl-4 text-right">
                <Link href={`/track?id=${o.id}`} className="text-sm font-semibold text-aqua-600 hover:underline dark:text-aqua-400">
                  Track
                </Link>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      <p className="mt-6 text-xs text-muted">
        Receipts download as PDF from each order in production (generated by the invoice service).
      </p>
    </div>
  );
}
